///////////////////////////////////////////////////////////////////////////                                                                     
// data_file_macros_gen.c
//
// Author: Gabriel Aguirre-Ollinger 
// Documentation start: 06.03.2020
// 
// Description:		 
//					 
//					 
// Modifications record:
//		
//
///////////////////////////////////////////////////////////////////////////


#include "data_file_macros_gen.h"

void
file_mgmt_macros_gen() {

	// Constants:
	const char  ASYNC_LOG_STR[]   = "async_log";
	const char  PAR_FILE_ID_STR[] = "par_file_id";

	// Macros file:
	static char	macros_filemg_path[LEN_NAME_MAX];
	FILE*		macros_filemg_id;

	// Variables master key file:
	static char key_file_path_master[LEN_NAME_MAX];
	FILE*		key_file_id_master;

	// Words array:
	char vars_file_words[N_WORDS_MAX][LEN_WORD_MAX];

	// Variables counters:
	int n_vars_sys;
	int start_idx_var, start_idx_par;
	int cnt_var, cnt_par;

	int v_i = 0;

	// int idx_var_type;
	int idx_var_name;
	int idx_var_len;
	int idx_var_active;

	char ref_char;

	/////////////////////////////////////////////////////////////
	// Variables info text file: read
	/////////////////////////////////////////////////////////////

	vars_file_read_help(vars_file_words, &n_vars_sys, &start_idx_var, &start_idx_par);

	/////////////////////////////////////////////////////////////
	// Macros file: initiate
	/////////////////////////////////////////////////////////////

	// Open macros text file:
	file_path_create(macros_filemg_path, APP_DIR, MACROS_FILE_MGMT_H, EXT_HEADER);
	macros_filemg_id = fopen(macros_filemg_path, "w");

	// Write file heading:
	fprintf(macros_filemg_id, "// %s%s \n", MACROS_FILE_MGMT_H, EXT_HEADER);	
	fprintf(macros_filemg_id, "\n");
	fprintf(macros_filemg_id, "// Auto-generated by script data_file_macros_gen.c/file_mgmt_macros_gen()\n");
	fprintf(macros_filemg_id, "// Author: Gabriel Aguirre-Ollinger\n");
	fprintf(macros_filemg_id, "\n");
	fprintf(macros_filemg_id, "#ifndef MACROS_FILE_MGMT\n");
	fprintf(macros_filemg_id, "#define MACROS_FILE_MGMT\n");

	/////////////////////////////////////////////////////////////
	// Set variable type counters (CRITICAL - only active vars will be counted):
	/////////////////////////////////////////////////////////////

	cnt_var = cnt_par = 0;

	/////////////////////////////////////////////////////////////
	// Macro: VARIABLES data write:
	/////////////////////////////////////////////////////////////

	fprintf(macros_filemg_id, "\n");
	fprintf(macros_filemg_id, "#define %s(%s) { %c\n", WRITE_DAT_SYS_STR, ASYNC_LOG_STR, CH_BKSLASH);

	for (v_i = start_idx_var; v_i < start_idx_par; v_i++) {
		idx_var_name	= N_FIELDS_VARS_FILE*v_i + 1;
		idx_var_len		= N_FIELDS_VARS_FILE*v_i + 2;
		idx_var_active	= N_FIELDS_VARS_FILE*v_i + 3;

		if (!strncmp(vars_file_words[idx_var_active], "1", 1)) { // only store active variables
			write_data_string_logger(macros_filemg_id,  vars_file_words[idx_var_name], vars_file_words[idx_var_len], NUM_DIGITS_PREC, ASYNC_LOG_STR);

			cnt_var++; // update var type counter
		}
	}

	fprintf(macros_filemg_id, "}\n");

	/////////////////////////////////////////////////////////////
	// Macro: PARAMETERS data write:
	/////////////////////////////////////////////////////////////

	fprintf(macros_filemg_id, "\n");
	fprintf(macros_filemg_id, "#define %s(%s) { %c\n", WRITE_PAR_SYS_STR, PAR_FILE_ID_STR, CH_BKSLASH);

	for (v_i = start_idx_par; v_i < n_vars_sys; v_i++) { 
		idx_var_name	= N_FIELDS_VARS_FILE*v_i + 1;
		idx_var_len		= N_FIELDS_VARS_FILE*v_i + 2;
		idx_var_active	= N_FIELDS_VARS_FILE*v_i + 3;

		if (!strncmp(vars_file_words[idx_var_active], "1", 1)) { // only store active variables
			write_data_string_fwrite(macros_filemg_id,  vars_file_words[idx_var_name], vars_file_words[idx_var_len], NUM_DIGITS_PREC, PAR_FILE_ID_STR);

			cnt_par++; // update var type counter
		}
	}

	fprintf(macros_filemg_id, "}\n");

	/////////////////////////////////////////////////////////////
	// Finish macros file:
	/////////////////////////////////////////////////////////////

	fprintf(macros_filemg_id, "\n");
	fprintf(macros_filemg_id, "#endif"); //	fprintf(macros_filemg_id, "#endif", MACROS_FILE_MGMT_H);
	
	// Close text file:
	fclose(macros_filemg_id);

	/////////////////////////////////////////////////////////////
	// Create master key file (text):
	/////////////////////////////////////////////////////////////

	// Open file:
	file_path_create(key_file_path_master, BASE_DIR, KEY_FNAME, EXT_TXT);
	key_file_id_master = fopen(key_file_path_master, "w");

	// Store variables' types counts:
	fprintf(key_file_id_master, "%d %d ", cnt_var, cnt_par);

	for (v_i = 0; v_i < n_vars_sys; v_i++) {
		idx_var_name	= N_FIELDS_VARS_FILE*v_i + 1;
		idx_var_len		= N_FIELDS_VARS_FILE*v_i + 2;
		idx_var_active	= N_FIELDS_VARS_FILE*v_i + 3;

		if (!strncmp(vars_file_words[idx_var_active], "1", 1)) { // only store active variables
			fprintf(key_file_id_master, "%s %s ", vars_file_words[idx_var_name], vars_file_words[idx_var_len]);
		}
	}

	// Close text file:
	fclose(key_file_id_master);
}


void
vars_file_read_help(char vars_file_words[][LEN_WORD_MAX], int* n_vars_sys,
					int* start_idx_var, int* start_idx_par) {

	const int DISP_ON = 1;

	// Variables info file:
	static char	vars_file_path[LEN_NAME_MAX];
	FILE*		vars_file_id;

	// Counters:
	int len_word, cnt_word;

	int cnt_var, cnt_par;
	int i;

	// Text string:
	const int LEN_TEXT_MAX = 5000; 
	char text[LEN_TEXT_MAX];

	/////////////////////////////////////////////////////////////
	// Open variables' info text file:
	/////////////////////////////////////////////////////////////

	file_path_create(vars_file_path, BASE_DIR, VARS_EDITABLE_FNAME, EXT_TXT);

	vars_file_id = fopen(vars_file_path, "r");

	if (vars_file_id == NULL) {
        printf("\n\nvars_file_read_help(): fopen of [%s] failed, errno = %d [%s]\n\n", vars_file_path, errno, strerror(errno));
		exit(0);
    }
	else
		printf("\nvars_file_read_help(): opened [%s]\n\n", vars_file_path);
	
	/////////////////////////////////////////////////////////////
	// Read text file:
	/////////////////////////////////////////////////////////////

	i = 0;
	while ((text[i] = getc(vars_file_id)) != EOF) 
		i++;
	text[i] = CH_EOS;

	fclose(vars_file_id);
	
	/////////////////////////////////////////////////////////////
	// Extract vars_file_words from text:
	/////////////////////////////////////////////////////////////

	cnt_word = cnt_var = cnt_par = 0;

	i = 0; 
	while (text[i] != CH_EOS) {
		// Skip over spaces, commas and returns:
		while (!is_alphanum(text[i])) 
			i++;

		// Copy any other characters as part of a word:
		len_word = 0;
		while (is_alphanum(text[i]))
			vars_file_words[cnt_word][len_word++] = text[i++];
		vars_file_words[cnt_word][len_word] = CH_EOS;

		// Keep cnt_word of each type of variable:
		if (     !strncmp(vars_file_words[cnt_word], DAT_STR, LEN_VAR_STR))
			cnt_var++;
		else if (!strncmp(vars_file_words[cnt_word], PAR_STR, LEN_VAR_STR))
			cnt_par++;

		if (text[i] != CH_EOS)
			cnt_word++;
	}

	*n_vars_sys = cnt_var + cnt_par;

	/////////////////////////////////////////////////////////////
	// Start indices for different var types:
	/////////////////////////////////////////////////////////////

	*start_idx_var = 0;
	*start_idx_par = cnt_var;

	if (DISP_ON) {
		for (i = 0 ; i < cnt_word ; i++) {
			printf("[%s] ", vars_file_words[i]);		
			if (i > 0 && !((i + 1) % N_FIELDS_VARS_FILE))
				printf("\n");
		}
	}
}

void
write_data_string_logger(FILE* file_id, char* var_name_str, char* var_length_str, int num_digits, char* logger_id) {
	if (strncmp(var_length_str, "1", 1)) // case for arrays
		fprintf(file_id, "   for (int i = 0; i < %s; i++)  %s->trace(\"{:.%df} \", %s[i]); %c\n",
			var_length_str, logger_id, num_digits, var_name_str, CH_BKSLASH);
				
	else  // case for scalar variables
		fprintf(file_id, "   %s->trace(\"{:.%df} \", %s); %c\n", 
			logger_id, num_digits, var_name_str, CH_BKSLASH);
}

void
write_data_string_fwrite(FILE* file_id, char* var_name_str, char* var_length_str, int num_digits, char* file_idstr) {
	char ref_char;

	if (strncmp(var_length_str, "1", 1)) // case for arrays
		ref_char = ' ';
	else
		ref_char = '&';

	fprintf(file_id, "   fwrite((double*)%c%s, sizeof(double), %s, %s);%c\n", 
		ref_char, var_name_str, var_length_str, file_idstr, CH_BKSLASH);
}

/////////////////////////////////////////////////////////////////////////////
// Ancillary functions:
/////////////////////////////////////////////////////////////////////////////

void 
file_path_create(char* file_path, char* f_dir, char* file_name, char* file_ext) {
	sprintf(file_path, "%s%s%s", f_dir, file_name, file_ext);
}

void 
copy_text_file(FILE* from_file_id, FILE* to_file_id) {
	const int LEN_TEXT_MAX = 1000;
	char text[LEN_TEXT_MAX];
	int  i = 0;
	char c;

	if (from_file_id == NULL) {
		printf("\n\n[%s] Invalid from_file_id\n", __FILE__);
		exit(0);
	}

	if (to_file_id == NULL) {
		printf("\n\n[%s] Invalid to_file_id\n", __FILE__);
		exit(0);
	}

	if ( fseek(from_file_id, 0L, SEEK_SET) != 0 ) { 
	  printf("\n\n[%s] file rewind failed\n", __FILE__);
	  exit(0);
	} 
	
	// Read text file:
	while ((c = fgetc(from_file_id)) != EOF) {
		// printf("%c\n", c);
		text[i] = c;
		i++;
	}
	text[i] = CH_EOS;

	// Write to new text file:
	fprintf(to_file_id, "%s", text);  
}

int 
is_alphanum(char ch) {
	return	ch != CH_SPACE && 
			ch != CH_COMMA && 
			ch != CH_TAB && 
			ch != CH_NEWLN &&
			ch != CH_EOS;
}

